### ISSUE TITLE
Failed to resolve module specifier "mutf-8"

### ISSUE THREAD

**Issue by PRO-2684** [Offroaders123/NBTify#49]
It seems that the module cannot be imported properly on the browser. The previous version (`1.90.1`) works fine.

![image](https://github.com/user-attachments/assets/8bc52088-fd2f-4042-b708-9ab2f47db728)

Environment: Windows 11 23H2, Edge 128.0.2739.54

**Comment by Offroaders123** [comment]
My bad, I still have to update the docs for loading the project with a CDN.

Here is the updated URL that allows you to load everything, including the new dependency I added, hence why it broke the module resolution in browsers.

```js
import("https://cdn.jsdelivr.net/npm/nbtify/+esm");
```
